sudo: required
services:
  - docker
before_install:
  - docker build -t viratarya/react-test -f ./client/Dockerfile.dev
script:
  - docker run viratarya/react-test npm test -- --cover

after_success:
  - docker build -t viratarya/multi-client ./client
  - docker build -t viratarya/multi-server ./server
  - docker build -t viratarya/multi-nginx ./nginx
  - docker build -t viratarya/multi-worker ./worker

  -echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID"
  - docker push viratarya/multi-client
  - docker push viratarya/multi-nginx
  - docker push viratarya/multi-server
  - docker push viratarya/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-923445559289'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY